/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BattingEntry {
    fours: bigint;
    notOut: boolean;
    runs: bigint;
    sixes: bigint;
    batsmanName: string;
    ballsFaced: bigint;
    dismissal: string;
}
export type Time = bigint;
export interface Delivery {
    ballNumber: bigint;
    wicket: boolean;
    runs: bigint;
    overNumber: bigint;
    extras: string;
    commentary: string;
}
export interface Innings {
    id: bigint;
    bowling: Array<BowlingEntry>;
    deliveries: Array<Delivery>;
    battingTeam: string;
    inningsNumber: bigint;
    totalRuns: bigint;
    bowlingTeam: string;
    oversBowled: bigint;
    matchId: bigint;
    wickets: bigint;
    extras: [bigint, bigint, bigint, bigint];
    batting: Array<BattingEntry>;
}
export interface BowlingEntry {
    maidens: bigint;
    overs: bigint;
    bowlerName: string;
    wickets: bigint;
    runsConceded: bigint;
}
export interface Match {
    id: bigint;
    status: MatchStatus;
    result?: string;
    teams: [string, string];
    title: string;
    createdAt: Time;
    innings: Array<Innings>;
    oversLimit?: bigint;
    format: MatchFormat;
}
export enum MatchFormat {
    odi = "odi",
    t20 = "t20",
    test = "test"
}
export enum MatchStatus {
    scheduled = "scheduled",
    completed = "completed",
    inProgress = "inProgress"
}
export interface backendInterface {
    addBattingEntry(inningsId: bigint, batsmanName: string): Promise<void>;
    addBowlingEntry(inningsId: bigint, bowlerName: string): Promise<void>;
    addDelivery(inningsId: bigint, overNumber: bigint, ballNumber: bigint, runs: bigint, extras: string, wicket: boolean, commentary: string): Promise<void>;
    createMatch(title: string, teamA: string, teamB: string, format: MatchFormat, oversLimit: bigint | null): Promise<bigint>;
    getMatch(matchId: bigint): Promise<Match>;
    getSampleDemoMatch(): Promise<Match>;
    listMatches(): Promise<Array<Match>>;
    startInnings(matchId: bigint, battingTeam: string, bowlingTeam: string): Promise<bigint>;
}
import type { Innings as _Innings, Match as _Match, MatchFormat as _MatchFormat, MatchStatus as _MatchStatus, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addBattingEntry(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBattingEntry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBattingEntry(arg0, arg1);
            return result;
        }
    }
    async addBowlingEntry(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBowlingEntry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBowlingEntry(arg0, arg1);
            return result;
        }
    }
    async addDelivery(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: string, arg5: boolean, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDelivery(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDelivery(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async createMatch(arg0: string, arg1: string, arg2: string, arg3: MatchFormat, arg4: bigint | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createMatch(arg0, arg1, arg2, to_candid_MatchFormat_n1(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMatch(arg0, arg1, arg2, to_candid_MatchFormat_n1(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async getMatch(arg0: bigint): Promise<Match> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatch(arg0);
                return from_candid_Match_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatch(arg0);
            return from_candid_Match_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSampleDemoMatch(): Promise<Match> {
        if (this.processError) {
            try {
                const result = await this.actor.getSampleDemoMatch();
                return from_candid_Match_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSampleDemoMatch();
            return from_candid_Match_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMatches(): Promise<Array<Match>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMatches();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMatches();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async startInnings(arg0: bigint, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.startInnings(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startInnings(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_MatchFormat_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchFormat): MatchFormat {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_MatchStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchStatus): MatchStatus {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Match_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Match): Match {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _MatchStatus;
    result: [] | [string];
    teams: [string, string];
    title: string;
    createdAt: _Time;
    innings: Array<_Innings>;
    oversLimit: [] | [bigint];
    format: _MatchFormat;
}): {
    id: bigint;
    status: MatchStatus;
    result?: string;
    teams: [string, string];
    title: string;
    createdAt: Time;
    innings: Array<Innings>;
    oversLimit?: bigint;
    format: MatchFormat;
} {
    return {
        id: value.id,
        status: from_candid_MatchStatus_n6(_uploadFile, _downloadFile, value.status),
        result: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.result)),
        teams: value.teams,
        title: value.title,
        createdAt: value.createdAt,
        innings: value.innings,
        oversLimit: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.oversLimit)),
        format: from_candid_MatchFormat_n10(_uploadFile, _downloadFile, value.format)
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    odi: null;
} | {
    t20: null;
} | {
    test: null;
}): MatchFormat {
    return "odi" in value ? MatchFormat.odi : "t20" in value ? MatchFormat.t20 : "test" in value ? MatchFormat.test : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scheduled: null;
} | {
    completed: null;
} | {
    inProgress: null;
}): MatchStatus {
    return "scheduled" in value ? MatchStatus.scheduled : "completed" in value ? MatchStatus.completed : "inProgress" in value ? MatchStatus.inProgress : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Match>): Array<Match> {
    return value.map((x)=>from_candid_Match_n4(_uploadFile, _downloadFile, x));
}
function to_candid_MatchFormat_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MatchFormat): _MatchFormat {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MatchFormat): {
    odi: null;
} | {
    t20: null;
} | {
    test: null;
} {
    return value == MatchFormat.odi ? {
        odi: null
    } : value == MatchFormat.t20 ? {
        t20: null
    } : value == MatchFormat.test ? {
        test: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
