/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MatchFormat = IDL.Variant({
  'odi' : IDL.Null,
  't20' : IDL.Null,
  'test' : IDL.Null,
});
export const MatchStatus = IDL.Variant({
  'scheduled' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Time = IDL.Int;
export const BowlingEntry = IDL.Record({
  'maidens' : IDL.Nat,
  'overs' : IDL.Nat,
  'bowlerName' : IDL.Text,
  'wickets' : IDL.Nat,
  'runsConceded' : IDL.Nat,
});
export const Delivery = IDL.Record({
  'ballNumber' : IDL.Nat,
  'wicket' : IDL.Bool,
  'runs' : IDL.Nat,
  'overNumber' : IDL.Nat,
  'extras' : IDL.Text,
  'commentary' : IDL.Text,
});
export const BattingEntry = IDL.Record({
  'fours' : IDL.Nat,
  'notOut' : IDL.Bool,
  'runs' : IDL.Nat,
  'sixes' : IDL.Nat,
  'batsmanName' : IDL.Text,
  'ballsFaced' : IDL.Nat,
  'dismissal' : IDL.Text,
});
export const Innings = IDL.Record({
  'id' : IDL.Nat,
  'bowling' : IDL.Vec(BowlingEntry),
  'deliveries' : IDL.Vec(Delivery),
  'battingTeam' : IDL.Text,
  'inningsNumber' : IDL.Nat,
  'totalRuns' : IDL.Nat,
  'bowlingTeam' : IDL.Text,
  'oversBowled' : IDL.Nat,
  'matchId' : IDL.Nat,
  'wickets' : IDL.Nat,
  'extras' : IDL.Tuple(IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat),
  'batting' : IDL.Vec(BattingEntry),
});
export const Match = IDL.Record({
  'id' : IDL.Nat,
  'status' : MatchStatus,
  'result' : IDL.Opt(IDL.Text),
  'teams' : IDL.Tuple(IDL.Text, IDL.Text),
  'title' : IDL.Text,
  'createdAt' : Time,
  'innings' : IDL.Vec(Innings),
  'oversLimit' : IDL.Opt(IDL.Nat),
  'format' : MatchFormat,
});

export const idlService = IDL.Service({
  'addBattingEntry' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'addBowlingEntry' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'addDelivery' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Bool, IDL.Text],
      [],
      [],
    ),
  'createMatch' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, MatchFormat, IDL.Opt(IDL.Nat)],
      [IDL.Nat],
      [],
    ),
  'getMatch' : IDL.Func([IDL.Nat], [Match], ['query']),
  'getSampleDemoMatch' : IDL.Func([], [Match], ['query']),
  'listMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
  'startInnings' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MatchFormat = IDL.Variant({
    'odi' : IDL.Null,
    't20' : IDL.Null,
    'test' : IDL.Null,
  });
  const MatchStatus = IDL.Variant({
    'scheduled' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Time = IDL.Int;
  const BowlingEntry = IDL.Record({
    'maidens' : IDL.Nat,
    'overs' : IDL.Nat,
    'bowlerName' : IDL.Text,
    'wickets' : IDL.Nat,
    'runsConceded' : IDL.Nat,
  });
  const Delivery = IDL.Record({
    'ballNumber' : IDL.Nat,
    'wicket' : IDL.Bool,
    'runs' : IDL.Nat,
    'overNumber' : IDL.Nat,
    'extras' : IDL.Text,
    'commentary' : IDL.Text,
  });
  const BattingEntry = IDL.Record({
    'fours' : IDL.Nat,
    'notOut' : IDL.Bool,
    'runs' : IDL.Nat,
    'sixes' : IDL.Nat,
    'batsmanName' : IDL.Text,
    'ballsFaced' : IDL.Nat,
    'dismissal' : IDL.Text,
  });
  const Innings = IDL.Record({
    'id' : IDL.Nat,
    'bowling' : IDL.Vec(BowlingEntry),
    'deliveries' : IDL.Vec(Delivery),
    'battingTeam' : IDL.Text,
    'inningsNumber' : IDL.Nat,
    'totalRuns' : IDL.Nat,
    'bowlingTeam' : IDL.Text,
    'oversBowled' : IDL.Nat,
    'matchId' : IDL.Nat,
    'wickets' : IDL.Nat,
    'extras' : IDL.Tuple(IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat),
    'batting' : IDL.Vec(BattingEntry),
  });
  const Match = IDL.Record({
    'id' : IDL.Nat,
    'status' : MatchStatus,
    'result' : IDL.Opt(IDL.Text),
    'teams' : IDL.Tuple(IDL.Text, IDL.Text),
    'title' : IDL.Text,
    'createdAt' : Time,
    'innings' : IDL.Vec(Innings),
    'oversLimit' : IDL.Opt(IDL.Nat),
    'format' : MatchFormat,
  });
  
  return IDL.Service({
    'addBattingEntry' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'addBowlingEntry' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'addDelivery' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Bool, IDL.Text],
        [],
        [],
      ),
    'createMatch' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, MatchFormat, IDL.Opt(IDL.Nat)],
        [IDL.Nat],
        [],
      ),
    'getMatch' : IDL.Func([IDL.Nat], [Match], ['query']),
    'getSampleDemoMatch' : IDL.Func([], [Match], ['query']),
    'listMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
    'startInnings' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };