/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BattingEntry {
  'fours' : bigint,
  'notOut' : boolean,
  'runs' : bigint,
  'sixes' : bigint,
  'batsmanName' : string,
  'ballsFaced' : bigint,
  'dismissal' : string,
}
export interface BowlingEntry {
  'maidens' : bigint,
  'overs' : bigint,
  'bowlerName' : string,
  'wickets' : bigint,
  'runsConceded' : bigint,
}
export interface Delivery {
  'ballNumber' : bigint,
  'wicket' : boolean,
  'runs' : bigint,
  'overNumber' : bigint,
  'extras' : string,
  'commentary' : string,
}
export interface Innings {
  'id' : bigint,
  'bowling' : Array<BowlingEntry>,
  'deliveries' : Array<Delivery>,
  'battingTeam' : string,
  'inningsNumber' : bigint,
  'totalRuns' : bigint,
  'bowlingTeam' : string,
  'oversBowled' : bigint,
  'matchId' : bigint,
  'wickets' : bigint,
  'extras' : [bigint, bigint, bigint, bigint],
  'batting' : Array<BattingEntry>,
}
export interface Match {
  'id' : bigint,
  'status' : MatchStatus,
  'result' : [] | [string],
  'teams' : [string, string],
  'title' : string,
  'createdAt' : Time,
  'innings' : Array<Innings>,
  'oversLimit' : [] | [bigint],
  'format' : MatchFormat,
}
export type MatchFormat = { 'odi' : null } |
  { 't20' : null } |
  { 'test' : null };
export type MatchStatus = { 'scheduled' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export type Time = bigint;
export interface _SERVICE {
  'addBattingEntry' : ActorMethod<[bigint, string], undefined>,
  'addBowlingEntry' : ActorMethod<[bigint, string], undefined>,
  'addDelivery' : ActorMethod<
    [bigint, bigint, bigint, bigint, string, boolean, string],
    undefined
  >,
  'createMatch' : ActorMethod<
    [string, string, string, MatchFormat, [] | [bigint]],
    bigint
  >,
  'getMatch' : ActorMethod<[bigint], Match>,
  'getSampleDemoMatch' : ActorMethod<[], Match>,
  'listMatches' : ActorMethod<[], Array<Match>>,
  'startInnings' : ActorMethod<[bigint, string, string], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];